import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menuderecho } from "@/componentes/Menuderecho";
import { Menuizquierdo } from "@/componentes/Menuizquierdo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My hoja de vida",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <div className="flex flex-col sm:flex-row min-h-screen">

          {/* Menú izquierdo - visible solo en pantallas medianas en adelante */}
          <aside className="hidden sm:block sm:max-w-[305px] w-full bg-white overflow-y-auto">
            <Menuizquierdo />
          </aside>

          {/* Contenido central */}
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>

          {/* Menú derecho - visible solo en pantallas grandes en adelante */}
          <aside className="hidden lg:block max-w-[100px] bg-white px-5 py-3 overflow-y-auto">
            <Menuderecho />
          </aside>
          
        </div>
      </body>
    </html>
  );
}
